### ISSUE TITLE
[COL] When updating from 1.3.7 to 1.3.9

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#24]
MC 1.12.2
Forge 2757
CV 1.3.9

https://pastebin.com/LFmLtikr

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Coherent Villages Mod Beta (coherentvillages)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at net.theexceptionist.coherentvillages.main.ClientProxy.registerRenderers(ClientProxy.java:86)
	at net.theexceptionist.coherentvillages.main.Main.init(Main.java:471)
```

**Comment by P3rf3ctXZer0** [comment]
I have the same crash.

**Comment by TheExceptionist** [comment]
Are you guys on a server?

**Comment by cursinorock** [comment]
same here, single play word.
[crash-2018-10-02_15.09.45-client.txt](https://github.com/TheExceptionist/Coherent-Villages/files/2439324/crash-2018-10-02_15.09.45-client.txt)

**Comment by P3rf3ctXZer0** [comment]
Nope on single player

**Comment by TheExceptionist** [comment]
Does it crash when the games loads? Or when you guys create a new world?

**Comment by drakray** [comment]
Sorry, Crash On Load

**Comment by drakray** [comment]
(I use [COL] in my titles for CrashOnLoad, force of habit lol)

**Comment by TheExceptionist** [comment]
Alright, well I have a new version coming out soon. Tell me if the problem persists... Because I'm not having the same problem

**Comment by TheExceptionist** [comment]
Check the releases area of GitHub

**Comment by drakray** [comment]
Will give it a minute, not visible yet(or is it private?)

**Comment by TheExceptionist** [comment]
https://github.com/TheExceptionist/Coherent-Villages/releases/tag/v1.3.12

**Comment by drakray** [comment]
No more Crash, thanks :)

**Comment by P3rf3ctXZer0** [comment]
ditto
